package com.controltower.app.audit.domain;

/**
 * Enumeration of all auditable actions in Control Tower.
 * Extend this enum when adding new sensitive operations.
 */
public enum AuditAction {

    // Identity
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    TOKEN_REFRESHED,

    // Tenant management
    TENANT_CREATED,
    TENANT_UPDATED,
    TENANT_SUSPENDED,
    TENANT_REACTIVATED,

    // User management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,

    // Client management
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_DELETED,
    BRANCH_CREATED,
    BRANCH_DELETED,

    // Licensing
    LICENSE_ACTIVATED,
    LICENSE_SUSPENDED,
    LICENSE_REACTIVATED,
    LICENSE_CANCELLED,
    FEATURE_FLAG_CHANGED,

    // Support
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_ESCALATED,
    TICKET_CLOSED,
    TICKET_DELETED,

    // Health
    HEALTH_RULE_CREATED,
    HEALTH_RULE_UPDATED,
    HEALTH_INCIDENT_OPENED,
    HEALTH_INCIDENT_RESOLVED,

    // Integrations
    INTEGRATION_CREATED,
    INTEGRATION_UPDATED,
    INTEGRATION_DELETED,
    SECRET_ROTATED,

    // Billing
    STRIPE_WEBHOOK_PROCESSED,
    SUBSCRIPTION_UPDATED,

    // Config
    CONFIG_CHANGED,

    // Kanban
    BOARD_CREATED,
    BOARD_DELETED,
    CARD_CREATED,
    CARD_MOVED,
    CARD_DELETED,
    CHECKLIST_TOGGLED,

    // Campaigns
    CAMPAIGN_CREATED,
    CAMPAIGN_SENT,
    CAMPAIGN_DELETED,

    // CRM - Client lifecycle
    CLIENT_STATUS_CHANGED,
    CLIENT_ASSIGNED_USER_CHANGED,
    CLIENT_SEGMENT_CHANGED,
    CLIENT_MOVED,
    PROSPECT_CONVERTED,
    PROSPECT_LOST,
    PROSPECT_REACTIVATED,

    // CRM - Branch
    BRANCH_STATUS_CHANGED,
    BRANCH_ASSIGNED_USER_CHANGED,

    // CRM - Opportunity
    OPPORTUNITY_STAGE_CHANGED,
    OPPORTUNITY_VALUE_CHANGED,
    OPPORTUNITY_ASSIGNED_USER_CHANGED,
    OPPORTUNITY_WON,
    OPPORTUNITY_LOST,
    OPPORTUNITY_REOPENED,

    // CRM - Contact
    CONTACT_CREATED,
    CONTACT_UPDATED,
    CONTACT_DELETED,
    CONTACT_ASSIGNED_USER_CHANGED,

    // CRM - Interactions
    INTERACTION_LOGGED,
    OPPORTUNITY_CREATED,
    OPPORTUNITY_UPDATED,

    // Proposals
    PROPOSAL_CREATED,
    PROPOSAL_UPDATED,
    PROPOSAL_SENT,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    PROPOSAL_EXPIRED,
    PROPOSAL_DELETED,

    // Finance reports
    FINANCE_REPORT_SENT,

    // Payroll / Nómina
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_TERMINATED,
    PAYROLL_PERIOD_CREATED,
    PAYROLL_PERIOD_PROCESSED,
    PAYROLL_PERIOD_PAID,
    PAYROLL_RECEIPT_SENT,

    // Generic
    CREATE,
    UPDATE,
    DELETE
}
